### ISSUE TITLE
Camera class for Basler camera

### ISSUE THREAD

**Issue by pedro-dreyer** [miguelgrinberg/flask-video-streaming#25]
Hi, I was trying to write a camera class to get images from a [Basler](https://www.baslerweb.com/en/products/cameras/area-scan-cameras/ace/aca1600-60gc/) camera.

The code seems to run fine for a while. However sometimes I get the following error:

Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/dreyer/git/flask-video-streaming/base_camera.py", line 93, in _thread
    for frame in frames_iterator:
  File "/home/dreyer/git/flask-video-streaming/camera_basler.py", line 19, in frames
    image = converter.Convert(grabResult)
  File "/usr/local/lib/python2.7/dist-packages/pypylon/pylon.py", line 6311, in Convert
    return _pylon.ImageFormatConverter_Convert(self, *args)
InvalidArgumentException: Cannot convert image. The passed source image is invalid. : InvalidArgumentException thrown (file 'ImageFormatConverter.cpp', line 77)

Any ideas what might be wrong? Thanks.

**Comment by miguelgrinberg** [comment]
This issue will be automatically closed due to being inactive for more than six months. Please reopen if you need more assistance.
