### ISSUE TITLE
Got an error when run app.py

### ISSUE THREAD

**Issue by QianshengGu** [miguelgrinberg/flask-video-streaming#29]
@miguelgrinberg Hi, when I download your code and run the code 'app.py'， but it can not display any images on the website, and an error occured as shown below:

Exception happened during processing of request from ('10.24.80.10', 49824)
Traceback (most recent call last):
  File "/home/macwg/ssd/anaconda2/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/macwg/ssd/anaconda2/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/macwg/ssd/anaconda2/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/home/macwg/ssd/anaconda2/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/home/macwg/ssd/anaconda2/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/home/macwg/ssd/anaconda2/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe

![tim 20181215164822](https://user-images.githubusercontent.com/33200440/50041077-c066e880-0089-11e9-8dc3-c4705a6ffd76.png)
![tim 20181215165147](https://user-images.githubusercontent.com/33200440/50041079-c361d900-0089-11e9-8d3d-edacb75deb93.png)

Can you tell me why and how to sovle? Thanks, best regards.

**Comment by miguelgrinberg** [comment]
The broken pipe error occurs when the client disconnects, so it is probably unrelated to the problem.

Which camera are you using?
