### ISSUE TITLE
remote camera over flask/opencv

### ISSUE THREAD

**Issue by dragonxtek** [miguelgrinberg/flask-video-streaming#9]
How I can stream rtsp with opencv?
I read that you can replace 0 (video source) with the file or url of the video.
I edited the following line from camera_opencv.py: 
video_source = 0
by
video_source = 'rtsp://video.crearchile.com:8080/live/canal2.mp4'
and I got this:
Starting camera thread.
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nboettcher/Downloads/rtsp/flask-video-streaming/base_camera.py", line 93, in _thread
    for frame in frames_iterator:
  File "/home/nboettcher/Downloads/rtsp/flask-video-streaming/camera_opencv.py", line 17, in frames
    raise RuntimeError('Could not start camera.')
RuntimeError: Could not start camera.

**Comment by miguelgrinberg** [comment]
Do you have opencv built with ffmpeg support? You likely need that to be able to read video files.

**Comment by dragonxtek** [comment]
Thanks!
I post a tutorial to configure opencv correctly and I mentioned your project as example
[https://installfights.blogspot.cl/2017/09/how-to-stream-rtsp-videos-or-mp4-files.html](https://installfights.blogspot.cl/2017/09/how-to-stream-rtsp-videos-or-mp4-files.html)
Now, how you can add width and height to resize the video/image on flask?

**Comment by GitStoph** [comment]
Will this work with RTSP camera feeds? Trying it at the moment and the result is:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/chmeisch/flask-video-streaming/base_camera.py", line 93, in _thread
    for frame in frames_iterator:
  File "/home/chmeisch/flask-video-streaming/camera_opencv.py", line 16, in frames
    raise RuntimeError('Could not start camera.')
RuntimeError: Could not start camera.
```

**Comment by miguelgrinberg** [comment]
If the camera isn't supported by opencv then it's not going to work.
